### PR TITLE
compose-local-store

### PR DESCRIPTION
**Pull request by biscon**
Changed ComposeLocalStore so that it will only subscribe and desubscribe once in a composition, no matter how many times the state is accessed. The previous version installed a GlobalStore listener per state access in the composable resulting in overhead and duplication of state diff logs (1 for each access to state getter in composable). Also made prevLocalValue "non nullable" so first state assignment will be properly logged.

@patrickusiewicz 
I love the design of rememberLocalStore but when I fixed the debug bug you found and started using it, I found out that it did a subscribe and separate state update for each access in the composable. This results in duplicate logging entries showing the same change, it also causes a lot of unnecessary state copying. 
I did some research and found the RememberObserver interface. Making the store implement this we get callbacks as the store is remembered and forgotten in the composition. This is imho ideal as the places to register and deregister with the GlobalStore. So I changed the implementation, but kept the interface. 
Anyway let me know what you think :)
I haven't changed the tests, far as I can tell they are still as valid (and they pass), but you might wanna check :)

Checkout and run the sample branch to check it in action

### CODE REVIEW

**Comment by patrickusiewicz** [comment]
I tried to reproduce the issue you found and I'm not sure what are the expected and actual outcomes 🙁 We need an unit test.
Even tough `RememberObserver` might solve the issue you found, it does leak functions from the `RememberObserver` interface. I would say that goes against the reason for we created the `ComposeLocalStore`, instead of reusing the existing `LocalStore` interface. 
Maybe we can come up with an alternative solution? But until then, I need to figure out how to reproduce the issue.

**Comment by patrickusiewicz** [comment]
I'm not sure, but I think I have reproduced the issue you found. It seems like there is a limitation with the current `rememberLocalStore` implementation. You need to access the `ComposeLocalStore.State` once and assign it to a local mutable variable like: 
`
val store: ComposeLocalStore<State, Action> = rememberLocalStore(
        globalStore,
        ...,
        ...
    )

val state = store.state
`
and then the debug info should work. If you access `ComposeLocalStore.state` property multiple times, you will experience the issue that you have encountered. But nothing prevents you from accessing the `ComposeLocalStore.state` property multiple times. This is obviously not a good design.
In the mean time Im trying to come up with an alternative solution.

**Comment by patrickusiewicz** [comment]
This:
```
interface ComposeLocalStore<Value, Action> {
    val state: State<Value>
    fun send(action: Action)
}

@Composable
inline fun <LocalValue, LocalAction, GlobalValue, reified GlobalAction, GlobalEnvironment> rememberLocalStore(
    globalStore: GlobalStore<GlobalValue, GlobalAction, GlobalEnvironment>,
    crossinline getLocalCopy: @DisallowComposableCalls (GlobalValue) -> LocalValue,
    crossinline getInitialValue: @DisallowComposableCalls (GlobalValue) -> LocalValue,
): ComposeLocalStore<LocalValue, LocalAction> {
    var prevLocalValue: LocalValue = remember { getInitialValue(globalStore.value) }

    val state = produceState(getInitialValue(globalStore.value)) {
        val stateChanger: ((GlobalValue) -> Unit) = { globalValue: GlobalValue ->

            val newLocalValue = getLocalCopy(globalValue)
            // Only update value if the local state have changed.
            if (prevLocalValue != newLocalValue) {
                if (BuildConfig.DEBUG) {
                    logStateDiff(prevLocalValue!!, newLocalValue!!)
                }
                value = newLocalValue
            }
            prevLocalValue = newLocalValue
        }

        globalStore.subscribe(stateChanger)

        awaitDispose {
            globalStore.desubscribe(stateChanger)
        }
    }

    val localStore = remember {
        object : ComposeLocalStore<LocalValue, LocalAction> {
            override fun send(action: LocalAction) {
                if (action is GlobalAction) {
                    globalStore.sendAction(action as GlobalAction)
                }
            }

            override val state: State<LocalValue> = state
        }
    }

    return localStore
}
```

seems to work. I don't know if there are any consequences of calling `produceState` inside of the `rememberLocalStore` function, instead of inside of the `state` property.

**Comment by biscon** [comment]
Closed and not merged

**Pull request closed without merging**
